/**
 * Created by wangze on 2016/10/18.
 */
export const UPDATE_LOADING = 'UPDATE_LOADING'
export const UPDATE_PATH_NAME = 'UPDATE_PATH_NAME'
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION'

export const UPDATE_CACHE_ORDER = 'UPDATE_CACHE_ORDER'
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS'
export const UPDATE_ADDRESS_ERROR = 'UPDATE_ADDRESS_ERROR'
export const UPDATE_ADDRESS_LIST = 'UPDATE_ADDRESS_LIST'
export const GET_ADDRESS_ERROR = 'GET_ADDRESS_ERROR'
export const UPDATE_SELECT_ADDRESS = 'UPDATE_SELECT_ADDRESS'

export const SET_OPENID = 'SET_OPENID'
export const SHOW_ALERT = 'SHOW_ALERT'
