/**
 * Created by wangze on 2016/10/18.
 */
export const UPDATE_LOADING = 'UPDATE_LOADING'
export const UPDATE_PATH_NAME = 'UPDATE_PATH_NAME'
export const UPDATE_DIRECTION = 'UPDATE_DIRECTION'

export const UPDATE_CACHE_ORDER = 'UPDATE_CACHE_ORDER'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'
export const UPDATE_ADDRESS_ERROR = 'UPDATE_ADDRESS_ERROR'
